name: Automerge

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Automerge Dependabot PR
        uses: eetu/action-automerge@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}